# Generated by Django 4.2.30 on 2026-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='审核意见')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '拒绝')], max_length=20, verbose_name='审核结果')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录管理',
                'db_table': 'project_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='项目名称')),
                ('category', models.CharField(max_length=100, verbose_name='项目类型')),
                ('college', models.CharField(max_length=100, verbose_name='所属学院')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='经费（元）')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申报时间')),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目管理',
                'db_table': 'research_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
